<a href="https://colab.research.google.com/github/GabrielCdev/Exploring_Numpy_Library/blob/main/Explorando_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Exercícios Numpy


1 - Importe a biblioteca numpy com o alias "np"

In [ ]:
import numpy as np

2 - Crie um array qualquer e informe o tamanho deste vetor em memória.

In [ ]:
x = np.arange(12)

print("{} bytes".format(x.size))
print("{} bytes".format(x.itemsize))

print("O tamanho do vetor em memória é: {} bytes".format(x.size * x.itemsize))

12 bytes
8 bytes
O tamanho do vetor em memória é: 96 bytes


3 - Reduza o tamanho do array anterior em memória sem alterar ou excluir nenhum dado e exiba o novo tamanho do array.

In [ ]:
type1 = x.dtype.name
print(type1)

x.astype(np.int32)

int64


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)

4 - Crie um vetor com valores de 10 a 49

In [ ]:
y = np.arange(10, 50)

y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

5 - Inverta o vetor anterior

In [ ]:
np.flip(y)
#y[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

6- Crie uma matriz 3x3 com valores que variam de 0 a 8

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7- Encontre índices de elementos diferentes de zero de [1,2,0,0,4,0] (dica: tem função pronta para isso)

In [ ]:
array = np.array([1,2,0,0,4,0])

print("Os índices dos elementos diferentes de 0 são {}".format(np.nonzero(array)))

Os índices dos elementos diferentes de 0 são (array([0, 1, 4]),)


8 - Crie uma matriz 10x10 com valores aleatórios e encontre os valores mínimo, máximo, média, moda e desvio padrão.

In [ ]:
from scipy import stats

np.random.seed()
z = np.random.random(size=(10,10))
print(z)

print("\nValor mínimo: {}".format(z.min()))
print("Valor máximo: {}".format(z.max()))
print("Média: {}".format(z.mean()))
print("Moda: {}".format(stats.mode(z)))
print("Desvio Padrão: {}".format(z.std()))

[[0.72265989 0.03862061 0.87429138 0.1460318  0.30905226 0.02808409
  0.75206948 0.11760809 0.56100264 0.57971928]
 [0.84881116 0.88580004 0.81430686 0.53008678 0.17873872 0.17268118
  0.62314713 0.11238513 0.79048202 0.43385871]
 [0.31677048 0.61366292 0.83645938 0.33251646 0.20704508 0.13516274
  0.09456715 0.41303206 0.45834517 0.26952357]
 [0.18528601 0.29938921 0.50577207 0.78959149 0.50696106 0.74508831
  0.00243633 0.75346558 0.89111179 0.7003428 ]
 [0.2349862  0.68375464 0.4378137  0.31847014 0.95332812 0.09426163
  0.16041897 0.78254564 0.05916232 0.86558989]
 [0.00324755 0.02529642 0.92237356 0.31266436 0.58943087 0.70797944
  0.72946545 0.3634564  0.81275812 0.77944967]
 [0.38979454 0.16632333 0.09373213 0.21888996 0.85176434 0.08215706
  0.77287645 0.08707153 0.6978707  0.09950879]
 [0.79495121 0.71722193 0.23251378 0.77542586 0.79566737 0.46182316
  0.17185819 0.68994605 0.34326144 0.67340745]
 [0.00323924 0.59482728 0.60350308 0.72661853 0.43573887 0.44674535
  0.44974857

9 - Dada uma matriz 1D, multiplique por 10 todos os elementos que estão entre 3 e 8.

In [ ]:
a = np.arange(11)
a[(a > 3) & (a < 8)] *= 10

a

array([ 0,  1,  2,  3, 40, 50, 60, 70,  8,  9, 10])

10 - Crie uma matriz 5x5 com valores de linha variando de 0 a 4

In [ ]:
np.random.seed()
np.random.randint(0,5, size=(5,5))

array([[3, 3, 1, 2, 0],
       [3, 3, 3, 2, 0],
       [1, 0, 3, 3, 4],
       [2, 0, 1, 0, 0],
       [1, 0, 1, 3, 0]])

11 - Crie um vetor de inteiros aleatório de tamanho 10 e ordene-o

In [ ]:
np.random.seed(2)
p = np.random.random(10)
print(p)

np.sort(p)

[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678  0.33033482
 0.20464863 0.61927097 0.29965467 0.26682728]


array([0.02592623, 0.20464863, 0.26682728, 0.29965467, 0.33033482,
       0.4203678 , 0.43532239, 0.4359949 , 0.54966248, 0.61927097])

12 - Crie o mesmo vetor da questão anterior (com o mesmo seed) e exiba a ordem de seus índices (função argsort)

In [ ]:
np.argsort(p)

array([1, 6, 9, 8, 5, 4, 3, 0, 2, 7])

13 - Crie um vetor aleatório de tamanho 10 e substitua o valor máximo por 0

In [ ]:
np.random.seed()

b = np.random.randint(30, size=10)
print(b)
print(np.max(b))

[11 14 23 14 13  4 25 14 29  1]
29


In [ ]:
b[np.argmax(b)] = 0
b

array([11, 14, 23, 14, 13,  4, 25, 14,  0,  1])

14 - Crie uma matriz 3x3 e exiba o índice e o valor de cada posição. (dica: consulte as funções np.ndenumerate e np.ndindex)

In [ ]:
np.random.seed()

matrix = np.random.randint(15, size=(3,3))
print(matrix)

[[2 0 5]
 [2 2 0]
 [2 1 4]]


In [ ]:
for index, x in np.ndenumerate(matrix):
  print(index, x)

(0, 0) 2
(0, 1) 0
(0, 2) 5
(1, 0) 2
(1, 1) 2
(1, 2) 0
(2, 0) 2
(2, 1) 1
(2, 2) 4


In [ ]:
for index in np.ndindex(matrix.shape):
  print(index, matrix[index])

(0, 0) 2
(0, 1) 0
(0, 2) 5
(1, 0) 2
(1, 1) 2
(1, 2) 0
(2, 0) 2
(2, 1) 1
(2, 2) 4


15 - Como ordenar uma matriz pela enésima coluna?

In [ ]:
np.random.seed()

to_order = np.random.randint(25, size=(5,5))
print(to_order)

[[21 20 23 15 10]
 [17 10 13  2  4]
 [14  3 14  9  8]
 [14  4 13 11 18]
 [24  0 22 11 15]]


In [ ]:
to_order[to_order[:, 3].argsort()]

array([[17, 10, 13,  2,  4],
       [14,  3, 14,  9,  8],
       [14,  4, 13, 11, 18],
       [24,  0, 22, 11, 15],
       [21, 20, 23, 15, 10]])